site_name: OpenCentauri
repo_url: https://github.com/suchmememanyskill/OpenCentauri
repo_name: OpenCentauri
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
plugins:
  - glightbox
  - git-committers:
      repository: suchmememanyskill/OpenCentauri
      branch: main
      enabled: !ENV [CI, false]
  - git-revision-date-localized:
      enable_creation_date: true
nav:
  - Home: index.md
  - Hardware:
    - CC1:
      - Hardware: hardware/CC1/index.md
      - Mainboard: hardware/CC1/mainboard.md
      - EMMC Tap Points: hardware/CC1/emmc-tapping.md
      - Toolhead: hardware/CC1/toolhead.md
      - Camera: hardware/CC1/camera.md
      - Bed: hardware/CC1/bed.md
      - Screen: hardware/CC1/screen.md
      - Miscellaneous: hardware/CC1/misc.md
    - CC2:
      - Hardware: hardware/CC2/index.md
      - Mainboard: hardware/CC2/mainboard.md
      - Toolhead: hardware/CC2/toolhead.md
      - Screen: hardware/CC2/screen.md
      - Miscellaneous: hardware/CC2/misc.md
      - CANVAS: hardware/CC2/CANVAS.md

  - Software: 
    - Software: software/index.md
    - Partitions: software/partitions.md
    - Updates: software/updates.md
    - API: software/api.md
    - Custom gcode: software/custom-gcode.md
    - Embedded Firmware: software/embedded-firmware.md
    - FEL: software/FEL-mode.md
  - Mods:
    - Machine Mods: mods/machine_mods.md
    - Printable Mods: mods/printable_mods.md
    - Light Mods: mods/light_mods.md
    - Klipper via mainboard replacement:
      - Main: klipper-via-mainboard-replacement/index.md
      - Recognize Hotend: klipper-via-mainboard-replacement/recognize-hotend.md
      - Printer Config: klipper-via-mainboard-replacement/printer-config.md
      - Mainsail Config: klipper-via-mainboard-replacement/mainsail-config.md
      - UDEV Setup: klipper-via-mainboard-replacement/udev-setup.md
    - Patched firmware:
      - Patched firmware: patched-firmware/index.md
      - Modified slicer machine gcode: patched-firmware/modified_start_end_machine_gcode.md
theme:
  name: material
  features:
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.tabs
    - navigation.expand
    - toc.integrate
    - content.code.copy
  palette:
  # Palette toggle for automatic mode
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/brightness-auto
      name: Switch to light mode

  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode

  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
    logo: material/cube 
extra:
  social:
    - icon: fontawesome/brands/discord
      link: https://discord.gg/t6Cft3wNJ3
extra_css:
  - extra.css
