name: build-bind-shell
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "bind-shell/**"

jobs:
  build:
    uses: ./.github/workflows/build-rust.yml
    with:
      project: bind-shell