name: build-dsp-to-serial
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "dsp-to-serial/**"

jobs:
  build:
    uses: ./.github/workflows/build-rust.yml
    with:
      project: dsp-to-serial