name: build-mcu-flasher
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "mcu-flasher/**"

jobs:
  build:
    uses: ./.github/workflows/build-rust.yml
    with:
      project: mcu-flasher