name: build-multiplexer
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "serial-multiplexer/**"

jobs:
  build:
    uses: ./.github/workflows/build-rust.yml
    with:
      project: serial-multiplexer