name: build-networktool
on:
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "wifi-network-config-tool/**"

jobs:
  build:
    uses: ./.github/workflows/build-rust.yml
    with:
      project: wifi-network-config-tool